Add Pipfile and log.py
weeding-nerdy/gufu_gud pull request #4
Opened 2021-01-01 19:06 UTC by ayan4m1

This PR adds a Pipfile that allows us to use [Pipenv](https://pipenv.pypa.io/en/latest/#install-pipenv-today) for dependency management. This automates the process of setting up a virtual environment and ensures that the correct dependencies are installed.

I have also broken out some of the notebook contents into a skeleton `log.py` which will capture data until Ctrl-C. Still need to add file write to it.

2021-01-06 06:37 UTC, weeding-nerdy requested changes
Overall it looks good, I left some comments, most fairly minor or style related.

Thanks again for all this work, it is very much appreciated!

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/Pipfile
> +autopep8 = "*"
Should we add `ipympl` and `ipykernel` to the dev-packages spec?

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/Pipfile
> +msgpack = "*"
Please also add `tqdm` to the packages.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/parse.py
> +    return decimated_df
Missing EOF New Line.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/parse.py
> +    decimated_df['t_quant'] = decimated_df.t.round(1)
Please add more comments.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/compare.py
> +print('Wrote compare.png')
Please add more comments.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/plot.py
> +print(f'Wrote temp-{filename}.png')
Please add more comments.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/log.py
> +    df.t -= df[df.p.gt(df.p.max() / 2.0)].t.iloc[0]
Since power is a derived quantity here, should this move to the parsing step as well like the resistance is?

I would propose we keep `df['t'] -= df.t.iloc[0]` and calculate the power/time-offset during parsing, but I am open to keeping it this way if there is a benefit.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/temp.py
> +def calculate_temp(df, resistance, material, method):
Should any of these parameters have default values?

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/temp.py
> +def calculate_temp(df, resistance, material, method):
Please add a docstring if you think this function will end up being used as part of the API for the module.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/temp.py
> +            t_cold + ((np.asarray(rr) - 1.0) / material))
Please move the return statement to this line as well.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/log.py
> +    df.t -= df[df.p.gt(df.p.max() / 2.0)].t.iloc[0]
Ah, it looks like the power is being re-computed in the parsing routine anyway.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/parse.py
> +    # Find values where power < 0.5 Watts
This might be my comment error, but that should be `>` not `<`

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/parse.py
> +    puff_length = (frame_count / data_rate) - (first_timestamp * -1)
Should be able to do something like this here, which is a bit simpler to me:
```python
puff_length = df.t.iloc[-1] - df.t.iloc[0]
```
Negative indexing is SUPER useful :-D

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/temp.py
> +            t_cold + ((np.asarray(rr) - 1.0) / material))
If you are doing this to reduce line length, just FYI a lot of python programmers use 120 columns as the max length these days instead of 80. Either is fine though.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/parse.py
> +    decimated_df['t_quant'] = decimated_df.t.round(1)
This looks like it is mostly code from the playground, so I can also comment this as well if you would prefer.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/gufugud/temp.py
> +        #         'ss316l': 879*10**-6  # delta_r/r per degree Celsius  # From Steam Engine calculator
This commented out line should probably be removed.

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/compare.py
> +    df['name'] = path[0:underscore_pos]
What is the purpose of this string manipulation? Does this require that the CSV file must have an `_` in the file name to work correctly?

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/log.py
> +    sys.exit(1)
If an argument is required, you can use the argparse module to do so by setting the `required` argument to `True`, like so:
```python
parser.add_argument(..., required=True, ...)
```

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/compare.py
> +  sys.exit(1)
I would recommend raising an exception here instead. Something like:
```python
raise ValueError(f'Must supply two or more paths! Paths given: {args.paths}')
```

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/plot.py
> +    sys.exit(1)
If an argument is required, you can use the argparse module to do so by setting the `required` argument to `True`, like so:
```python
parser.add_argument(..., required=True, ...)
```

2021-01-06 06:37 UTC, weeding-nerdy commented on gg_analyze/log.py
> +                    print(f'Rejecting {obj}\t{chr(obj)}', flush=True)
I would replace this with `print(f'Rejecting {obj}', flush=True)` the chr part was for debug

2021-01-13 20:00 UTC, ayan4m1 commented on gg_analyze/compare.py
> +    df['name'] = path[0:underscore_pos]
Yes, the goal is to allow you to graph multiple series, so to keep track of which is which we need a series name for the legend. This does mean that a filename would need to contain an `_` but `log.py` always produces one.

2021-01-13 20:08 UTC, ayan4m1 commented
OK, I think I took care of all your comments. Thanks!

2021-01-16 20:38 UTC, weeding-nerdy requested changes
I saw a few updates, but there are still several comments and questions that haven't been addressed. Have you forgotten to push the latest changes?

2021-01-16 20:38 UTC, weeding-nerdy commented on gg_analyze/compare.py
> +    df['name'] = path[0:underscore_pos]
Ok, can you document the required filename format, or put in code to handle files that do not have an underscore?

2021-01-30 18:54 UTC, weeding-nerdy commented on gg_analyze/log.py
> +parser.add_argument('device', help='Device name', required=True)
`required` is incompatible with positional arguments, positional arguments are always required by default.

2021-01-30 19:40 UTC, weeding-nerdy commented on gg_analyze/plot.py
> +df = temp.calculate_temp(df, args.resistance, 'ss316l', 'tfr')
Can this be refactored to support the ESCC as well?

2021-01-30 19:41 UTC, weeding-nerdy commented on gg_analyze/compare.py
> +    temp.calculate_temp(df, args.resistance, 'ss316l', 'tfr')
Can this be refactored to support the ESCC as well?

2021-04-17 21:59 UTC, ayan4m1 commented on gg_analyze/gufugud/temp.py
> +            t_cold + ((np.asarray(rr) - 1.0) / material))
Is there a way to set autopep8 line length in source control?

2021-04-17 22:20 UTC, weeding-nerdy approved these changes
LGTM, feel free to hit that merge button!

2021-04-17 22:28 UTC, merged